### ISSUE TITLE
Add option for non-breaking lines

### ISSUE THREAD

**Issue by ccarse** [springmeyer/arc.js#13]
On https://www.mapbox.com/mapbox.js/example/v1.0.0/cross-date-line/ you'll notice the comment:

> The coordinate -233.9 is technically invalid but Leaflet permits it because it can imply the direction of wrapping - to wrap in a direction, you can add or subtract 360 from the desired end coordinate

It would be nice if arc.js could generate lines with coordinates like that. If this is something you'd accept in a pull request let me know, I could possibly take a look at it but I can make no promises, my js is very weak.

Thanks, 
Cody

**Comment by jgravois** [comment]
an implementation of the suggestion in https://github.com/springmeyer/arc.js/issues/13#issuecomment-44318714 would still be welcome, but i'm closing in the name of housekeeping.
