### ISSUE TITLE
generator.Arc() is not as described in README

### ISSUE THREAD

**Issue by vincentbernat** [springmeyer/arc.js#19]
In README, it is said:

```
> line
{ properties: { name: 'Seattle to DC' },
  coords: 
   [ [ -122, 48.00000000000001 ],
     [ -112.06161978373486, 47.7241672604096 ],
     [ -102.38404317022653, 46.60813199882492 ],
     [ -93.22718895342909, 44.716217302635705 ],
     [ -84.74823988299501, 42.14415510795357 ],
     [ -77, 38.99999999999999 ] ],
  length: 6 }
```

This is not the case. There is a geometries object which is an array with one member which is an object containing `cords` and `length` properties as described above.

Dunno if the problem is in README or in the implementation.

**Comment by jgravois** [comment]
fix proposed in #45. thank you both.
