### ISSUE TITLE
Add license information to the README and repository

### ISSUE THREAD

**Issue by kottmann** [springmeyer/arc.js#22]
I would like to use arc.js to draw a great circle on a map. To be able to use this in our project I need to know if the license your are releasing this under gives me the right to do that.

Please add the license to the github repository and mention the license in the README.

If have haven't decided yet on a license I am happy to help with that.

**Comment by matiassingers** [comment]
@kottmann according to [`package.json#L21-L25`](https://github.com/springmeyer/arc.js/blob/98c425c96cbf3c709f8cecfa971ca1debd76f733/package.json#L21-L25) it's BSD.

But it would be great for @springmeyer to re-confirm this.

**Comment by kottmann** [comment]
That would be nice. I am happy to send a pull request to add a LICENSE file containing the BSD license and an update to the README to shortly mention that.

**Comment by springmeyer** [comment]
done, thanks for noticing.
