### ISSUE TITLE
How to make a dashed or dotted curved line

### ISSUE THREAD

**Issue by prateekgng** [springmeyer/arc.js#24]
I am creating map using leaflet. I am able to draw solid curve line but could not draw dashed or dotted curve line.

Any leads would be appreciated

**Comment by tmcw** [comment]
This is outside the scope of arc.js, which only does the math to compute an arc. What you're looking for is the [Leaflet documentation](http://leafletjs.com/reference.html), specifically the [Path options](http://leafletjs.com/reference.html#path) that you can provide as the second argument to the [Polyline](http://leafletjs.com/reference.html#polyline) constructor.
