### ISSUE TITLE
Incorrect README (or incorrect package.json ;-))

### ISSUE THREAD

**Issue by slybridges** [springmeyer/arc.js#25]
Instead of:
`$ npm install --save arc.js`

`README.md` should read:
`$ npm install --save arc`

Alternatively, should you want to remain consistent with Bower, `package.json` name should be called `arc.js` and republished on NPM.

Thanks for the lib !

**Comment by tmcw** [comment]
Thanks! Fixed in 19ec3d3e5581792ce4a26c5305e34c4cc5f4e8d0
