### ISSUE TITLE
Ability to color arcs?

### ISSUE THREAD

**Issue by sskadamb** [springmeyer/arc.js#30]
Hi, 

I was looking around to see if there is a way to color arcs in arc options, but I couldn't find it. Have I just missed it or would I be messing around with the js myself? 

Thanks!

**Comment by tmcw** [comment]
arc.js only creates the raw geometries required to draw arcs - it doesn't display the arcs itself. Typically, you'll use a library like Leaflet to display the geometries generated by arc.js, and use that library's options - like [Path options](http://leafletjs.com/reference.html#path) - to change color or other options.

**Comment by sskadamb** [comment]
Oh, I see due to my inexperience with arc.js I did not realize I could just do that! Thanks for the reply, I fixed the issue.
