### ISSUE TITLE
arcGenerator.Arc(100,{offset:10}),how do i set these two argument?

### ISSUE THREAD

**Issue by JoyTiann** [springmeyer/arc.js#37]
very close line,for example [114.376688,30.4619172],[113.844623,30.237268],i use arcGenerator.Arc(100,{offset:10}) to produce a line, it seem like a straight line, it has not arc, so how do i set these two argument that i can produce a arc line?
I am waiting for your reply,please.

**Comment by JoyTiann** [comment]
i notice arc.js from openlayer example(https://openlayers.org/en/latest/examples/flight-animation.html),but from the example ,we can see between two close point, it seem like a straight line, but i want to produce a arc line ,i guess it depends on arcGenerator.Arc(100,{offset:10}), so  i want to know how do i set the two argument?

**Comment by jgravois** [comment]
sorry for the late reply.

this library doesn't provide a mechanism to exaggerate or suppress the bend of an arc between a start and end point. the greater the distance between an origin and destination, the more pronounced the arc will be when projected onto a mercator map.

closing, but happy to discuss further.
