### ISSUE TITLE
make 'main' the default (protected) branch?

### ISSUE THREAD

**Issue by jgravois** [springmeyer/arc.js#49]
these days you don't need to maintain a `gh-pages` branch in order to wire up [GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

if @springmeyer feels like giving me admin keys to this repo i'd be interested in making `main` the default branch and setting up [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) to disable `-f` pushing, etc.

**Comment by springmeyer** [comment]
Happy to give you admin access. But it appears that, given this repo is in my personal account (rather than an org), I'm not able to give you admin.

**Comment by springmeyer** [comment]
So perhaps share the steps you'd recommend and I can run it out?

**Comment by jgravois** [comment]
> this repo is in my personal account (rather than an org)

i forgot about that little snag 😄 

Settings > Branches
* the ✏️ lets you rename the default branch
* <kdb>Add Rule</kbd> lets you define what is allowed for `main` or any other branch.

there are lots of options to enforce security. at a minimum i find it helpful to disable force pushing and ensure that the commit history for the repo can't be overwritten.

<img width="995" alt="Screen Shot 2022-07-09 at 9 10 06 PM" src="https://user-images.githubusercontent.com/3011734/178130987-dc392627-47be-4498-96e7-062648222968.png">

Settings > Pages
I *think* this one will update automatically when you rename the default branch, but it'd be worthwhile to doublecheck.
<img width="464" alt="Screen Shot 2022-07-09 at 9 10 20 PM" src="https://user-images.githubusercontent.com/3011734/178130980-db7139bf-4ade-4beb-af38-1fd6d0a327c8.png">

thanks for humoring me. none of this is mission critical.

**Comment by springmeyer** [comment]
Thanks, all done!
