### ISSUE TITLE
Support for Decimal Precision

### ISSUE THREAD

**Issue by KD33** [springmeyer/arc.js#51]
Is it possible to provide decimal precision as an option to generator.Arc?  I'm working on optimizing a workflow that requires drawing a lot of lines.  One of the optimizations I am making is to limit the precision of coordinate values (suggested by MapBox under the section Cleaning up your data https://docs.mapbox.com/help/troubleshooting/working-with-large-geojson-data/).

Trimming the precision at the same time that the coordinates are generated would save me the trouble of having to iterate through the coordinates after

Thanks

**Comment by jgravois** [comment]
given that this isn't remotely professional grade surveying, my gut reaction is that the library would be best off rounding to 6 decimal places internally and calling it a day. happy to discuss alternatives if anyone has concerns though.

**Comment by KD33** [comment]
That works.  Thanks

**Comment by KD33** [comment]
> a PR for this would be welcome. i don't plan on tackling it myself.


Sure.  See [PR 52](https://github.com/springmeyer/arc.js/pull/52)

**Comment by jgravois** [comment]
closed by #53 (better late than never)
